# generated by maixhub, tested on maixpy3 v0.4.8
# copy files to TF card and plug into board and power on
import sensor, image, lcd, time
import KPU as kpu
from machine import UART
import gc, sys
from fpioa_manager import fm

input_size = (224, 224)
#labels = ['cardboard', 'paper', 'bottle', 'battery'] #原
#anchors = [2.34, 2.31, 1.98, 4.12, 3.78, 3.25, 5.31, 5.03, 1.28, 1.12]   #原
labels = ['bottle', 'battery', 'cardboard', 'paper']
anchors = [1.28, 1.12, 3.38, 1.41, 2.19, 2.73, 4.47, 2.25, 3.88, 4.0]
fm.register(26, fm.fpioa.UART1_TX, force=True)
uart = UART(UART.UART1, 9600, 8,0,1,timeout=1000,read_buf_len=4096)    #设置波特率，数组长度

'''def sending_data(x):
    FH = bytearray([x,0x5B])
    uart.write(FH);'''
def send_header():
    uart.write(bytearray([0xAA, 0xBB]))  # 发送帧头

def sending_data(center_x, center_y, obj_id):
    send_header()  # 先发送帧头

    data = bytearray([center_x, center_y, obj_id, 0x5B])  # 结束标志 0x5B
    uart.write(data)

'''def sending_head():
    FH = bytearray([0x2C,0x12])
    uart.write(FH);'''

id_mapping = {
        0: 2,  # bottle
        1: 3,  # battery
        2: 0,  # cardboard
        3: 1   # paper
    }


def lcd_show_except(e):
    import uio
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=input_size)
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

'''class Comm:
    def __init__(self, uart):
        self.uart = uart

    def send_detect_result(self, objects, labels):
        msg = ""
        for obj in objects:
            pos = obj.rect()
            p = obj.value()
            idx = obj.classid()
            label = labels[idx]
            msg += "{}:{}:{}:{}:{}:{:.2f}:{}, ".format(pos[0], pos[1], pos[2], pos[3], idx, p, label)
        if msg:
            msg = msg[:-2] + "\n"
        self.uart.write(msg.encode())

def init_uart():
    fm.register(10, fm.fpioa.UART1_TX, force=True)
    fm.register(11, fm.fpioa.UART1_RX, force=True)

    uart = UART(UART.UART1, 115200, 8, 0, 0, timeout=1000, read_buf_len=256)
    return uart
'''

def main(anchors, labels = None, model_addr="/sd/m.kmodel", sensor_window=input_size, lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(sensor_hmirror)
    sensor.set_vflip(1)
    sensor.run(1)

    lcd.init(type=1)
    lcd.rotation(lcd_rotation)
    lcd.clear(lcd.WHITE)

    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    try:
        img = image.Image("startup.jpg")
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)

    #uart = init_uart()
    #comm = Comm(uart)

    try:
        task = None
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.5, 0.3, 5, anchors) # threshold:[0,1], nms_value: [0, 1]
        while(True):
            img = sensor.snapshot()
            #t = time.ticks_ms()
            objects = kpu.run_yolo2(task, img)
            #t = time.ticks_ms() - t
            #plist=objects[:]
            #pmax=max(plist)       #获得最大概率值
            #max_index=plist.index(pmax)         #获得最大概率值的索引
            if objects:
                for obj in objects:
                    pos = obj.rect()
                    # 计算目标的中心坐标
                    center_x = pos[0] + pos[2] // 2
                    center_y = pos[1] + pos[3] // 2
                    #obj_id = obj.classid()+1 #原
                    obj_id = id_mapping[obj.classid()] + 1
                    # 画出检测框和中心点
                    img.draw_rectangle(pos)
                    img.draw_cross(center_x, center_y, color=(0, 255, 0), size=5)
                    img.draw_string(pos[0], pos[1], "%s : %.2f" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))
                    # 发送数据到 STM32
                    sending_data(center_x, center_y, obj_id)
                    print("Sent: [Header] center_x=%d, center_y=%d, obj_id=%d" % (center_x, center_y, obj_id))
                    #comm.send_detect_result(objects, labels)
                    #print("pos is (%d, %d, %d, %d)  obj is %d" % (pos[0], pos[1], pos[2], pos[3], obj.classid()))

            #img.draw_string(0, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
            #img.draw_string(0, 2, "Upgrade to MaixCAM to use YOLOv8", scale=1.2, color=(255, 0, 0))
            #img.draw_string(0, 30, "wiki.sipeed.com/maixcam", scale=1.2, color=(255, 0, 0))
            lcd.display(img)
            #sending_head()     #发送帧头
            time.sleep_ms(100)  #间隔100ms
            '''if(max_index==0 or max_index==2 or max_index==7):
                sending_data(1)
            elif(max_index==1 or max_index==6 or max_index==8 or max_index==9):
                sending_data(2)
            elif(max_index==3 or max_index==4):
                sending_data(3)
            elif(max_index==5):
                sending_data(4)'''
    except Exception as e:
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)


if __name__ == "__main__":
    try:
         main(anchors = anchors, labels=labels, model_addr=0x300000, lcd_rotation=0)
        #main(anchors = anchors, labels=labels, model_addr="/sd/model-183232.kmodel")
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
